config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq)
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :urls do
    collection do
      get 'url_list'
      get 'bookmarklet'
      get 'search'
    end
    member do
      get :qr
    end
  end

  resources :users do
    collection do
      get :cas_logout
    end
  end

  root to: redirect('/urls')

  # So anything that doesn't match the resource controllers or the root path
  # goes to the redirector controller.

  get '/redirector/invalid' => 'redirector#invalid'

  get '/toggle_mode' => 'theme#toggle_mode'

  get '/:id' => 'redirector#index', as: :shortened, id: /.*/

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/url.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: urls
#
#  id         :integer          not null, primary key
#  auto       :boolean          default(TRUE)
#  clicks     :integer          default(0)
#  shortened  :string(255)
#  to         :string(10240)    not null
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#
# Indexes
#
#  index_urls_on_auto       (auto)
#  index_urls_on_clicks     (clicks)
#  index_urls_on_shortened  (shortened)
#  index_urls_on_to         (to)
#  index_urls_on_user_id    (user_id)
#
class Url < ApplicationRecord
  include ActiveModel::Validations

  belongs_to :user, optional: true

  before_create :generate_url

  validates :to, length: { maximum: 10.kilobytes }, allow_blank: false
  validates :to, presence: true
  validate :to do
    errors.add(:to, "cannot be 'localhost' or '#{REDIRECT_DOMAIN}'.") if
      to&.match(PROTECTED_REDIRECT_REGEX)
    errors.add(:to, 'must be a valid url') unless valid_url?(to)
  end
  validates :shortened, shortcode: true, on: %i[create update]

  scope :auto, -> { where(auto: true) }
  scope :mine, ->(u) { where(user_id: u.id) }
  scope :not_mine, ->(u) {
    where.not(user_id: u.id).or(Url.default_scoped.where(user_id: nil))
  }

  def self.search(search)
    if search
      where(
        'lower(shortened) like lower(?) OR lower("to") like lower(?)',
        "%#{search}%", "%#{search}%"
      )
    else
      all
    end
  end

  # Don't let shortcodes be overwritten with blank data.
  def shortened=(value)
    return if value.blank?

    super
  end

  # Ensure protocol appears exactly once.
  def to=(value)
    if value.present?
      protocols = value.scan(%r{https?://})
      protocol = protocols.last || 'https://'

      base_url = value.gsub(%r{https?://}, '')
      value = "#{protocol}#{base_url}"
    end

    super
  end

  private

  def valid_url?(url)
    !!URI.parse(url)
  rescue URI::InvalidURIError
    false
  end

  def generate_url
    if shortened.present?
      self.auto = false
    else
      self.auto = true
      self.shortened = create_shortcode
    end
  end

  def create_shortcode
    shortened = random_shortcode

    until Url.where(shortened: shortened).empty?
      shortened = random_shortcode
    end

    shortened
  end

  def suffix
    # These will never be used by Base32 encoding, so it's pretty unlikely
    # they'll occur giving us a high probability of matching with only one
    # character.
    %w[i l o u].sample
  end

  def random_shortcode
    (0...6).map { (65 + rand(26)).chr }.join
  end
end

app/controllers/urls_controller.rb
# frozen_string_literal: true

class UrlsController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :authenticate_user!

  def bookmarklet
    @page_title = "Shorten a URL - #{REDIRECT_DOMAIN}"
  end

  def show
    @url = Url.find url_params[:id]
  end

  def index
    @page_title = "Shorten a URL - #{REDIRECT_DOMAIN}"

    search = url_params[:search]&.strip&.tr(' ', '-')
    redirect_to search_urls_path(search: search) if search.present?

    hilite

    @not_my_urls = organized(Url.not_mine(current_user), :others_page)
    @my_urls = organized(Url.mine(current_user), :my_page)
  end

  def search
    @page_title = "Shorten a URL - #{REDIRECT_DOMAIN}"

    hilite

    @not_my_urls = organized(Url.not_mine(current_user).search(url_params[:search]), :others_page)
    @my_urls = organized(Url.mine(current_user).search(url_params[:search]), :my_page)

    render 'index'
  end

  # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
  def create
    @url = Url.new(
      shortened: url_params[:url][:shortened],
      to: url_params[:url][:to],
      user: current_user
    )

    respond_to do |f|
      f.html do
        if @url.save
          flash[:notice] = "Shortened URL (#{root_url}#{@url.shortened}) was successfully created."
        else
          logger.warn(@url.errors.inspect)
          flash[:error] = "ERROR: #{@url.errors.full_messages}"
        end
      end
    end

    redirect_to urls_path
  end
  # rubocop:enable Metrics/MethodLength, Metrics/AbcSize

  def edit
    @url = Url.find(params[:id])
    authorize! :update, @url
  end

  def update
    @url = Url.find(params[:id])
    authorize! :update, @url

    if @url.update(update_url_params)
      redirect_to urls_path
    else
      render 'edit'
    end
  end

  def destroy
    @url = Url.find(params[:id])
    authorize! :destroy, @url
    @url.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  def qr
    url = Url.find(params[:id])
    qrcode = RQRCode::QRCode.new(shortened_url(url.shortened))

    png = qrcode.as_png(
      bit_depth: 1,
      border_modules: 1,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: 'black',
      file: nil,
      fill: 'white',
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 400,
    )

    send_data png, type: 'image/png', disposition: 'inline', filename: "brkmn-qr-#{url.shortened}.png"
  end

  private

  def url_params
    params.permit(
      :id, :search, :my_page, :others_page, :per_page, :sort, :direction,
      url: %i[shortened to]
    )
  end

  def update_url_params
    params.permit(url: :to)[:url]
  end

  def sort_column
    sort = url_params[:sort] || session[:sort]

    session[:sort] = sort if url_params[:sort] != session[:sort]

    %w[shortened "to" clicks created_at].include?(sort) ? sort : 'shortened'
  end

  def sort_direction
    direction = url_params[:direction] || session[:direction]

    session[:direction] = direction if url_params[:direction] != session[:direction]

    %w[asc desc].include?(direction) ? direction : 'asc'
  end

  def organized(relation, page_indicator)
    relation.order(sort_column + ' ' + sort_direction)
            .paginate(
              page: url_params[page_indicator],
              per_page: url_params[:per_page]
            )
  end

  # rubocop:disable Metrics/MethodLength
  def hilite
    case url_params[:sort] || session[:sort]
    when '"to"'
      @to_header = 'to hilite'
      @clicks_header = 'clicks'
      @shortened_header = 'shortened'
      @created_header = 'created_at'
    when 'clicks'
      @clicks_header = 'clicks hilite'
      @to_header = 'to'
      @shortened_header = 'shortened'
      @created_header = 'created_at'
    when 'created_at'
      @clicks_header = 'clicks'
      @to_header = 'to'
      @shortened_header = 'shortened'
      @created_header = 'created_at hilite'
    else
      @shortened_header = 'shortened hilite'
      @clicks_header = 'clicks'
      @to_header = 'to'
      @created_header = 'created_at'
    end
  end
  # rubocop:enable Metrics/MethodLength
end

app/views/urls/_url_list.html.erb
<tr>
  <td class="shortened">
    <div>
      <div class="shortened-title">
        <%= link_to(url_list.shortened, shortened_url(url_list.shortened)) %>
      </div>
      <div class="shortened-actions">
        <div>
          <a class="urls-table-clipboard"
            title="Click to copy to clipboard"
            data-action="click->urls-table#copy"
            data-url="<%= shortened_url(url_list.shortened) %>">
            <%= image_tag('clipboard.svg', title: 'Copy url to clipboard') %>
          </a>
        </div>

        <div>
          <%= link_to(qr_url_path(url_list), target: '_blank', title: 'Show QR code for this url') do %>
            <%= image_tag('qr.svg') %>
          <% end %>
        </div>

        <div>
          <% if can?(:update, url_list) %>
            <%= link_to(edit_url_path(url_list), title: 'Edit', data: { turbo: false }) do %>
              <%= image_tag('edit.svg') %>
            <% end %>
          <% end %>

          <% if can?(:destroy, url_list) %>
            <%= link_to(url_path(url_list), title: 'Delete', method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this?" }) do %>
              <%= image_tag('delete.svg') %>
            <% end %>
          <% end %>
        </div>
      </div>

    </div>
  </td>
  <td class="arrow">→</td>
  <td class="to">
    <%= link_to(url_list.to, url_list.to) %>
  </td>
  <td class="created">
    <%= url_list.created_at.strftime("%Y-%m-%d %H:%M") %>
  </td>
  <td class="clicks">
    <%= url_list.clicks %>
  </td>
</tr>

app/views/urls/bookmarklet.html.erb
<%= render partial: 'shared/add_url' %>

app/views/urls/edit.html.erb
<div class="edit-form">
  <h4 class="is-size-4">URL Details</h4>

  <%= form_for(@url) do |f| %>
    <% if @url.errors.any? %>
      <div id="error">
        <% @url.errors.full_messages.each do |msg| %>
          <div class="error"><%= msg %></div>
        <% end %>
      </div>
    <% end %>

    <%= f.label :to, 'Full URL' %>
    <%= f.text_field :to %>
    <br>
    <br>

    <%= f.label :shortened, 'Shortened URL' %>
    <%= @url.shortened %>
    <br>
    <br>

    <%= f.label :clicks, 'Clicks' %>
    <%= @url.clicks %>
    <br>
    <br>

    <%= f.submit 'Update' %>
  <% end %>
</div>

app/views/urls/index.html.erb
<%= render partial: 'shared/add_url' %>

<hr>

<turbo-frame id="my_urls_frame" data-turbo-action="advance">
  <div id="my_urls" data-controller="urls-table">
    <h4 class="is-size-4">
      <div>My URLs</div>
    </h4>

    <div class="urls-table-wrapper">
      <% if @my_urls.present? %>
        <%= render 'shared/url_list', urls: @my_urls, page_param: :my_page %>
      <% else %>
        <div class="notification">
          There are no URLs to display.
        </div>
      <% end %>
    </div>
  </div>
</turbo-frame>

<hr>

<turbo-frame id="not_my_urls_frame" data-turbo-action="advance">
  <div id="not_my_urls" data-controller="urls-table">
    <h4 class="is-size-4">
      <div>All URLs</div>
    </h4>

    <div class="urls-table-wrapper">
      <% if @not_my_urls.present? %>
        <%= render 'shared/url_list', urls: @not_my_urls, page_param: :others_page %>
      <% else %>
        <div class="notification">
          There are no URLs to display.
        </div>
      <% end %>
    </div>
  </div>
</turbo-frame>

app/views/urls/search.html.erb
<%= render 'shared/add_url' %>
<%= render 'shared/search' %>

<% unless @urls.nil? %>
  <%= render 'shared/url_list', urls: @urls %>
<% end %>

app/views/urls/show.html.erb
<fieldset>
  <legend>URL Details</legend>
  <%= form_for(@url) do |f| %>
    <%= f.label :to, 'Full URL: ' %>
    <%= @url.to %>
    <br>
    <br>
    <%= f.label :shortened, 'Shortened URL: ' %>
    <%= @url.shortened %>
    <br>
    <br>
    <%= f.label :clicks, 'Clicks: ' %>
    <%= @url.clicks %>
    <br>
    <br>
  <% end %>
  <%= link_to "Home", urls_path, class: 'back' %>
</fieldset>