config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq)
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :urls do
    collection do
      get 'url_list'
      get 'bookmarklet'
      get 'search'
    end
    member do
      get :qr
    end
  end

  resources :users do
    collection do
      get :cas_logout
    end
  end

  root to: redirect('/urls')

  # So anything that doesn't match the resource controllers or the root path
  # goes to the redirector controller.

  get '/redirector/invalid' => 'redirector#invalid'

  get '/toggle_mode' => 'theme#toggle_mode'

  get '/:id' => 'redirector#index', as: :shortened, id: /.*/

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/theme_controller.rb
# frozen_string_literal: true

class ThemeController < ApplicationController
  def toggle_mode
    current_mode = cookies[:viewing_mode] == 'classic' ? 'modern' : 'classic'
    cookies[:viewing_mode] = { value: current_mode, expires: 1.year.from_now }

    respond_to do |format|
      format.html { render 'toggle_mode' }
    end
  end
end

app/views/theme/_toggle_link.html.erb
<%= link_to toggle_mode_path,
    id: 'toggle-link',
    data: {
      controller: 'theme',
      action: 'theme#toggle',
      'current-mode': viewing_mode,
      'light-image': asset_path('classicmode.svg'),
      'classic-image': asset_path('modernmode.svg'),
    } do %>
  <span>
    <%= image_tag("#{viewing_mode == 'classic' ? 'modern' : 'classic'}mode.svg") %>
  </span>
  <span>
    <%= viewing_mode == 'classic' ? 'Light' : 'Classic' %>
  </span>
<% end %>

app/views/theme/toggle_mode.html.erb
<turbo-frame id="viewing-mode-toggle">
  <%= render 'toggle_link', viewing_mode: viewing_mode %>
</turbo-frame>