config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq)
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :urls do
    collection do
      get 'url_list'
      get 'bookmarklet'
      get 'search'
    end
    member do
      get :qr
    end
  end

  resources :users do
    collection do
      get :cas_logout
    end
  end

  root to: redirect('/urls')

  # So anything that doesn't match the resource controllers or the root path
  # goes to the redirector controller.

  get '/redirector/invalid' => 'redirector#invalid'

  get '/toggle_mode' => 'theme#toggle_mode'

  get '/:id' => 'redirector#index', as: :shortened, id: /.*/

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_add_url.html.erb
<div class="add-form">
  <h4 class="is-size-4">Shorten a URL</h4>

  <%= form_for(Url.new(to: (params[:url].blank?) ? 'https://' : params[:url][:to])) do |f| %>
    <div class="messages" style="display: none;"></div>
    <div>
      <%= f.text_field(:to, placeholder: "URL to shorten", tabindex: 1) %>
      <%= f.submit('Shorten', tabindex: 3, id: 'submit') %>
    </div>
    <div>
      <%= "#{root_url}" %>
      <%= f.text_field(:shortened, placeholder: "OPTIONAL: shorten to. . . ", tabindex: 2) %>
    </div>
  <% end %>
</div>

app/views/shared/_search.html.erb
<div class="search <% if params[:search].present? %>header-items-item-search-active<% end %>" data-search-target="searchForm">
  <%= form_tag search_urls_path, method: 'get', class: 'search-form', data: { turbo: false } do %>
    <div>
      <%= text_field_tag :search, params[:search] %>
    </div>
    <div>
      <%= submit_tag 'Search', class: 'search_button', id: 'search_button' %>
    </div>
    <div>
      <%= link_to 'Clear', root_url, search: nil %>
    </div>
  <% end %>
</div>

app/views/shared/_url_list.html.erb
<table>
  <tr class="top_pagination">
    <td colspan="6">
      <%= will_paginate urls, param_name: page_param %>
    </td>
  </tr>
  <tr>
    <th class="<%= @shortened_header %>"><%= sortable 'shortened', 'Shortened URL' %></th>
    <th class="arrow"></th>
    <th class="<%= @to_header %>"><%= sortable '"to"', 'Full URL' %></th>
    <th class="<%= @created_header %>"><%= sortable 'created_at', 'Created' %></th>
    <th class="<%= @clicks_header %>"><%= sortable 'clicks', 'Clicks' %></th>
  </tr>
  <%= render partial: 'urls/url_list', collection: urls %>
  <tr class="bottom_pagination">
    <td colspan="6">
      <%= will_paginate urls, param_name: page_param %>
    </td>
  </tr>
</table>