config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq)
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :urls do
    collection do
      get 'url_list'
      get 'bookmarklet'
      get 'search'
    end
    member do
      get :qr
    end
  end

  resources :users do
    collection do
      get :cas_logout
    end
  end

  root to: redirect('/urls')

  # So anything that doesn't match the resource controllers or the root path
  # goes to the redirector controller.

  get '/redirector/invalid' => 'redirector#invalid'

  get '/toggle_mode' => 'theme#toggle_mode'

  get '/:id' => 'redirector#index', as: :shortened, id: /.*/

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= capybara_lockstep if defined?(Capybara::Lockstep) %>
    <title><%= @page_title.blank? ? REDIRECT_DOMAIN : @page_title %></title>
    <meta name="apple-mobile-web-app-title" content="Brkmn">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="turbo-prefetch" content="false">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="<%= image_url('icon.png') %>" type="image/png">
    <link rel="apple-touch-icon" href="<%= image_url('icon.png') %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= viewing_mode == 'classic' ? 'viewing-mode-classic' : 'viewing-mode-light' %> <%= controller.controller_name %>">
    <div class="wrapper">
      <div class="main-inner">
        <% if @current_user %>
          <div class="header-items">
            <div class="header-items-item">
              <a
                class="header-items-item-bookmarklet"
                title="Drag this link to your bookmarks toolbar to shorten any page via <%= REDIRECT_DOMAIN %>"
                href="javascript:(function(){f='<%= bookmarklet_urls_url %>?url%5bto%5d='+encodeURIComponent(window.location.href)+'&';a=function(){if(!window.open(f+'noui=1&jump=doclose','brkmn','location=1,links=0,scrollbars=0,toolbar=0,width=1000,height=400'))location.href=f+'jump=yes'};if(/Firefox/.test(navigator.userAgent)){setTimeout(a,0)}else{a()}})()"
              >
                <span>
                  <%= image_tag('bookmark.svg') %>
                </span>
                <span>
                  Shorten on <%= REDIRECT_DOMAIN %>
                </span>
              </a>
            </div>
            <div class="header-items-item">
              <div class="header-items-item-search" data-controller="search">
                <a data-controller="search" data-action="click->search#toggle">
                  <%= image_tag('search.svg') %>
                  <span>
                    Search
                  </span>
                </a>

                <%= render partial: 'shared/search' %>
              </div>

              <%= render 'theme/toggle_link' %>

              <span>
                <%= image_tag('user.svg') %>
                <span class="header-items-item-user">
                  <%= @current_user.email %>
                </span>
              </span>

              <span>
                <% if Rails.application.config.devise_auth_type == 'cas' %>
                  <%= link_to 'Sign out', cas_logout_users_path, method: :get, data: { turbo: false } %>
                <% else %>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
                <% end %>
              </span>
            </div>
          </div>
        <% end %>

        <h1 class="site-title is-size-2">
          <a href="<%= root_path %>" class="header-logo-link">
            <% if File.exist?(Rails.root.join('app', 'assets', 'images', 'logo.png')) %>
              <%= image_tag('logo.png', class: 'header-logo-image') %>
            <% end %>
            <%= REDIRECT_DOMAIN %>
          </a>
        </h1>

        <% flash.each do |name, msg| %>
          <div class="message" id="<%= name %>">
            <%= msg %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>

    <footer>
      <%= ENV['FOOTER_TEXT'] || 'Berkman Klein Center for Internet & Society' %>
    </footer>
  </body>
</html>